"FCLR", "FNEG", "FABS",
"FHWD", "RDW1",
"RDW2",
"FAS",  "FSS",  "FDS",  "FMS",
"FSRS", "FLDS",
"FATS", "FSTS", "FDTS", "FMTS",
"FNRM", "FMTF", "FMFT",
"RDW3",
"RDW4",
"FAD",  "FSD",  "FDD",  "FMD",
"FSCL", "FSRD", "FLDX", "FLDD",
"FATD", "FSTD", "FDTD", "FMTD",
"FCLK", "FRST", "FWST",
