"FCLR", "FNEG", "FABS",
"FHWD", "F1WD",
"F2WD",
"FAS",  "FSS",  "FDS",  "FMS",
"FSRS", "FLDS",
"FATS", "FSTS", "FDTS", "FMTS",
"FNRM", "FMTF", "FMFT",
"F3WD",
"F4WD",
"FAD",  "FSD",  "FDD",  "FMD",
"FSCL", "FSRD", "FLDX", "FLDD",
"FATD", "FSTD", "FDTD", "FMTD",
"FCLK", "FRST", "FWST",
